# Generated by fusen: do not edit by hand

# library(ggplot2)
# ggplot() + geom_point()

test_that("say_hello works", {
  expect_message(say_hello(), regexp = "Hello Berra")
  expect_message(say_hello(someone = "Seb"), "Hello Seb")
  # test the output
  hello_anna <- say_hello(someone = "Anna")
  expect_equal(hello_anna, "Hello Anna")
})
