# Generated by fusen: do not edit by hand

#' Say hello to someone
#'
#' @param someone Character. The name of the person you want to say hello to
#'
#' @return Side effect: A message in the console
#' 
#' @importFrom glue glue
#' 
#' @export
#'
#' @examples
#' say_hello() # Hello Berra
#' say_hello(someone = "Seb") # Hello Seb
#' 
#' hello_anna <- say_hello(someone = "Anna") 
#' hello_anna
#' # library(ggplot2)
#' # ggplot() + geom_point()
say_hello <- function(someone = "Berra") {
  text <- glue('Hello {someone}')
  message(text)
  return(text)
}
